# Copyright 2025 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

controller:
  image:
    repository: quay.io/metallb/controller
    tag: v0.14.9

speaker:
  image:
    repository: quay.io/metallb/speaker
    tag: v0.14.9
