# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# This secret will be used if sso is disabled, instead of the templated one in uds-package.yaml. 
# MetalLB needs to mount the secret and creating it this way avoids creating an unnecessary 
# client in the keycloak realm and unnecessary secret data in the cluster.
{{- if not .Values.sso.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sso.secretName }}
  namespace:  {{ .Release.Namespace }}
type: "Opaque"
stringData:
  metallb.sso.config.key: |
    example.saml.enabled: {{ .Values.sso.enabled }}
{{- end }}
